In [ ]:
image1 = np.array([[4,2,3],[5,5,4]])
image2 = np.array([[3,1,2],[6,7,9]])

print('images before reshaping')
print(image1)
print(image2)

print(image1.shape)
print(image2.shape)

print('images after reshaping')
image1 = image1.reshape(1,2,3)
image2 = image2.reshape(1,2,3)

print(image1)
print(image2)

print(image1.shape)
print(image2.shape)

print('Merging along axis = 1')
X = np.stack((image1,image2),axis=1) 

print()
print('X: ',X)
print(X.shape)

print('Squeezing along axis = 1')tensor_hit = tensor_hit.reshape(1,x_size,y_size)
Y = np.squeeze(X,axis = 0)
print(Y)
print(Y.shape)
print(image2.shape)

#        [6, 7]])
Z = np.concatenate((Y,image2),axis=0)
print(Z)
print(Z.shape)
# X = np.stack((,image2),axis=1)
# array([[[[4, 2],
#          [5, 5]],
#         [[3, 1],
#         [6, 7]]]])

# np.shape(X)         
# X = X.reshape((2,2,2))   
# X 
# array([[[4, 2],
#         [5, 5]],
#        [[3, 1],
#         [6, 7]]])

# X[0] # image 1
# array([[4, 2],
#        [5, 5]])
# X[1] # image 2
# array([[3, 1], 